In [1]:
# import relevant libraries
import numpy as np

In [2]:
# create an empty numpy array & save in a variable
array0 = np.array([])
array0

array([], dtype=float64)

In [3]:
# initialize list1 as a Python list
list1 = [1, 2, 3, 4, 5]

In [4]:
# create a one-dimensional numpy array from list1 & save in a variable
array1 = np.array(list1)
array1

array([1, 2, 3, 4, 5])

In [5]:
# initialize list2 as a nested Python list
list2 = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [6]:
# create a two-dimensional numpy array from list2 
array2 = np.array(list2)
array2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
# create a numpy array containing integers 0 to 4 including 0 and 4
np.arange(5)

array([0, 1, 2, 3, 4])

In [8]:
# create a numpy array containing all even integers between 0 and 10 including 0 and 10
np.arange(0, 11, 2)

array([ 0,  2,  4,  6,  8, 10])

In [9]:
# create a one-dimenstional numpy array containing 5 zeros
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [10]:
# create a two-dimensional numpy array of zeros having 4 rows and 5 columns
np.zeros((4, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [11]:
# create a one-dimenstional numpy array containing 6 ones
np.ones(6)

array([1., 1., 1., 1., 1., 1.])

In [12]:
# create a two-dimensional numpy array of ones having 4 rows and 6 columns
np.ones((4, 6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [13]:
# create a numpy array of 9 evenly spaced numbers from 1 to 2, including 1 and 2
np.linspace(1, 2, 9)

array([1.   , 1.125, 1.25 , 1.375, 1.5  , 1.625, 1.75 , 1.875, 2.   ])

In [14]:
# create a numpy array of 10 random integers from 20 to 50
np.random.randint(20, 50, 10)

array([28, 34, 40, 26, 45, 34, 20, 40, 27, 32])

In [15]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### method to check for an empty array in NumPy

In [16]:
arr = np.array([])
arr.size == 0 # 0=empty

True

#### check whether a pandas data frame is empty or not?

In [ ]:
df.empty

#### sort an array in NumPy by the nth column?

In [19]:
array2[array2[:,1].argsort()]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

#### Explain the usage of decorators
Decorators in Python are used to modify or inject code in functions or classes. Using decorators, you can wrap a class or function method call so that a piece of code can be executed before or after the execution of the original code. Decorators can be used to check for permissions, modify or track the arguments passed to a method, logging the calls to a specific method, etc.

In [26]:
def multipliers():
    return [lambda x: i * x for i in range (4)]
    print [m(2) for m in multipliers ()]

SyntaxError: invalid syntax (<ipython-input-26-226892543592>, line 3)

The output for the above code will be [6, 6,6,6]. The reason for this is that because of late binding the value of the variable i is looked up when any of the functions returned by multipliers are called.

In [29]:
list= [1,2,3,4,5]
print (list[8:])

[]


In [30]:
list[8]

IndexError: list index out of range

In [31]:
list[8:]

[]

In [32]:
def foo (i= []): # default is empty, if has specific values, use the value
    i.append (1)
    return i

In [33]:
foo()

[1]

In [34]:
foo() # Argument to the function foo is evaluated only once when the function is defined

[1, 1]

In [36]:
i = [1,2,3,4,5]
foo(i) 

[1, 2, 3, 4, 5, 1]

In [39]:
tinytuple = (123, 'john')
print(tinytuple*2)

(123, 'john', 123, 'john')


In [41]:
tuple2 = ('Hello')
tuple2 + tinytuple

TypeError: can only concatenate str (not "tuple") to str

In [44]:
x = '123 hello'
repr(x)

"'123 hello'"

In [45]:
eval(x)

SyntaxError: unexpected EOF while parsing (<string>, line 1)

In [46]:
frozenset(x)

frozenset({' ', '1', '2', '3', 'e', 'h', 'l', 'o'})

In [47]:
choice(x)

NameError: name 'choice' is not defined

In [53]:
from random import random
random.randrange(11)

AttributeError: 'builtin_function_or_method' object has no attribute 'randrange'

In [54]:
random()  # random number between 0-1

0.83972790623742

In [55]:
randrange(0, 101, 2) 

NameError: name 'randrange' is not defined