In [1]:
# import relevant libraries
import numpy as np

In [2]:
# initialize arrayA as a numpy array 
# representing the scores of participants in a competition
scores = np.random.randint(50, 101, 200)

In [3]:
# compute the median of scores
np.median(scores)

75.0

In [4]:
# compute the mean of scores
np.mean(scores)

75.235

In [5]:
# compute the variance of scores
np.var(scores)

225.74977499999997

In [6]:
# compute the standard deviation of scores
np.std(scores)

15.024971713783689

In [7]:
arr = np.array([[1,2,3,4],[4,5,7,3]])

In [8]:
arr

array([[1, 2, 3, 4],
       [4, 5, 7, 3]])

In [9]:
arr.mean() # average of all elements

3.625

In [10]:
np.mean(arr)

3.625

In [11]:
arr.mean(axis=0) # average of each column

array([2.5, 3.5, 5. , 3.5])

In [12]:
np.mean(arr,axis=0)

array([2.5, 3.5, 5. , 3.5])

In [13]:
arr.mean(axis=1) # average of each row

array([2.5 , 4.75])

In [14]:
np.mean(arr,axis=1)

array([2.5 , 4.75])