In [1]:
# import relevant libraries
import numpy as np

In [2]:
array0 = np.array([])

In [3]:
# find the shape of array0
array0.shape

(0,)

In [10]:
array1 = np.array([1, 2, 3, 4, 5])
array1

array([1, 2, 3, 4, 5])

In [5]:
# find the shape of array1
array1.shape

(5,)

In [11]:
array2 = np.array([[1, 2, 3,5], [4, 5, 6,7], [7, 8, 9,5]])

In [12]:
# find the shape of array2
array2.shape

(3, 4)

In [8]:
array_zeros = np.zeros((4, 5))

In [9]:
# find the shape of array_zeros
array_zeros.shape

(4, 5)

In [13]:
array_ones = np.ones((3, 6))

In [14]:
# find the shape of array_ones
array_ones.shape

(3, 6)

In [15]:
array_r0 = np.random.randint(1, 50, 25)
array_r0

array([22, 12, 20,  5, 15, 35, 14,  6, 49,  1,  2, 30, 20, 15, 38, 28, 43,
        9, 45, 34, 14, 28, 21, 20, 19])

In [16]:
# find the shape of array_r0
array_r0.shape

(25,)

In [17]:
# reshape array_r0 
# to create a new multi-dimensional numpy array 
# containing array_r0's items with 5 rows & 5 columns
array_r0.reshape((5, 5))

array([[22, 12, 20,  5, 15],
       [35, 14,  6, 49,  1],
       [ 2, 30, 20, 15, 38],
       [28, 43,  9, 45, 34],
       [14, 28, 21, 20, 19]])

In [18]:
# note that array_r0 itself was not modified
array_r0

array([22, 12, 20,  5, 15, 35, 14,  6, 49,  1,  2, 30, 20, 15, 38, 28, 43,
        9, 45, 34, 14, 28, 21, 20, 19])

In [19]:
array_r1 = np.random.randint(1, 50, 20)
array_r1

array([13, 16, 31, 19, 41, 31,  7, 42, 37, 19, 16, 10,  5, 13, 26, 16, 41,
       18, 22, 34])

In [20]:
# find the shape of array_r1
array_r1.shape

(20,)

In [21]:
# reshape array_r1
# to create a new multi-dimensional numpy array containing array_r1's items 
# with 10 rows & 2 columns
array_r1.reshape((10, 2))

array([[13, 16],
       [31, 19],
       [41, 31],
       [ 7, 42],
       [37, 19],
       [16, 10],
       [ 5, 13],
       [26, 16],
       [41, 18],
       [22, 34]])

In [22]:
# reshape array_r1
# to create a new multi-dimensional numpy array containing array_r1's items 
# with 2 rows & 10 columns
array_r1.reshape((2, 10))

array([[13, 16, 31, 19, 41, 31,  7, 42, 37, 19],
       [16, 10,  5, 13, 26, 16, 41, 18, 22, 34]])

In [23]:
# reshape array_r1
# to create a new multi-dimensional numpy array containing array_r1's items 
# with 4 rows & 5 columns
array_r1.reshape((4, 5))

array([[13, 16, 31, 19, 41],
       [31,  7, 42, 37, 19],
       [16, 10,  5, 13, 26],
       [16, 41, 18, 22, 34]])

In [24]:
# reshape array_r1
# to create a new multi-dimensional numpy array containing array_r1's items 
# with 5 rows & 4 columns
array_r1.reshape((5, 4))

array([[13, 16, 31, 19],
       [41, 31,  7, 42],
       [37, 19, 16, 10],
       [ 5, 13, 26, 16],
       [41, 18, 22, 34]])

In [25]:
# note that array_r1 itself was not modified
array_r1

array([13, 16, 31, 19, 41, 31,  7, 42, 37, 19, 16, 10,  5, 13, 26, 16, 41,
       18, 22, 34])

In [26]:
array_r2 = np.random.randint(1, 50, (4, 4))
array_r2

array([[24, 17, 12, 10],
       [40, 24,  7,  3],
       [39, 47, 30, 31],
       [40, 28, 49, 17]])

In [27]:
# find the shape of array_r2
array_r2.shape

(4, 4)

In [28]:
# reshape array_r2 
# to create a new one-dimensional numpy array containing array_r2's items 
# with length 16
array_r2.reshape(16)

array([24, 17, 12, 10, 40, 24,  7,  3, 39, 47, 30, 31, 40, 28, 49, 17])

In [29]:
# note that array_r2 itself was not modified
array_r2

array([[24, 17, 12, 10],
       [40, 24,  7,  3],
       [39, 47, 30, 31],
       [40, 28, 49, 17]])

In [31]:
array_r3 = np.random.randint(1, 50, 10)

In [33]:
array_r3

array([24, 46,  4, 48,  1, 47, 46, 44, 10,  7])

In [34]:
array_r3.shape

(10,)

In [35]:
arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('shape of array :', arr.shape)

[[[[[1 2 3 4]]]]]
shape of array : (1, 1, 1, 1, 4)


In [37]:
arr2 = np.zeros((3,4))
arr2

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [38]:
arr3 = arr2.reshape(2,3,2)

In [39]:
arr3

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [40]:
arr3.base  # not none means arr3 is related to arr2, one change will affect another

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [41]:
arr3[0,0,1] = 10

In [42]:
arr3

array([[[ 0., 10.],
        [ 0.,  0.],
        [ 0.,  0.]],

       [[ 0.,  0.],
        [ 0.,  0.],
        [ 0.,  0.]]])

In [43]:
arr2

array([[ 0., 10.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

In [44]:
arr2[1,2] = 100

In [45]:
arr2

array([[  0.,  10.,   0.,   0.],
       [  0.,   0., 100.,   0.],
       [  0.,   0.,   0.,   0.]])

In [46]:
arr3

array([[[  0.,  10.],
        [  0.,   0.],
        [  0.,   0.]],

       [[100.,   0.],
        [  0.,   0.],
        [  0.,   0.]]])

In [47]:
arr3.reshape(-1)

array([  0.,  10.,   0.,   0.,   0.,   0., 100.,   0.,   0.,   0.,   0.,
         0.])

In [48]:
arr3.reshape(2,6,-1) # -1 means the system will calculate this dimension

array([[[  0.],
        [ 10.],
        [  0.],
        [  0.],
        [  0.],
        [  0.]],

       [[100.],
        [  0.],
        [  0.],
        [  0.],
        [  0.],
        [  0.]]])