### If we iterate on a n-D array it will go through n-1th dimension one by one.

In [1]:
import numpy as np

In [2]:
arr = np.random.randint(1,100,20) # choose random 20 numbers between 1 ~ 100

In [3]:
arr

array([89, 71, 15, 50, 98, 82, 15,  4, 44, 57, 90, 29, 67, 94, 70, 83,  7,
       62, 98, 41])

In [4]:
# iterate through arr
for i in arr:
    print(i)

89
71
15
50
98
82
15
4
44
57
90
29
67
94
70
83
7
62
98
41


In [5]:
arr2 = arr.reshape(4,5)

In [6]:
for j in arr2:
    print(j)

[89 71 15 50 98]
[82 15  4 44 57]
[90 29 67 94 70]
[83  7 62 98 41]


In [7]:
arr3 = arr.reshape(2,2,5)

In [10]:
for m in arr3:
    print("m represents the 2-D array:")
    print(m)

m represents the 2-D array:
[[89 71 15 50 98]
 [82 15  4 44 57]]
m represents the 2-D array:
[[90 29 67 94 70]
 [83  7 62 98 41]]


### To get scalars, use n*for statements for n dimensions or np.nditer()

In [9]:
for i in arr3:
    for j in i:
        for t in j:
            print(t)

89
71
15
50
98
82
15
4
44
57
90
29
67
94
70
83
7
62
98
41


In [11]:
for j in np.nditer(arr3):
    print(j)

89
71
15
50
98
82
15
4
44
57
90
29
67
94
70
83
7
62
98
41


### Out put a different type 

#### NumPy does not change the data type of the element in-place (where the element is in array) so it needs some other space to perform this action, that extra space is called buffer, and in order to enable it in nditer() we pass flags=['buffered']

In [12]:
arr2 = np.array([1, 2, 3])

for x in np.nditer(arr2, flags=['buffered'], op_dtypes=['S']):
  print(x)

b'1'
b'2'
b'3'


In [13]:
arr2 = np.array([1, 2, 3])

for x in np.nditer(arr2, flags=['buffered'], op_dtypes=['str']):
  print(x)

1
2
3


### Iterating With Different Step Size

In [14]:
arr3 = np.array([[1,2,3,4],[5,6,7,8],[9,10,12,12]])

for i in arr3[:,::2]:  # all rows, all columns, step=2
    print(i)

[1 3]
[5 7]
[ 9 12]


In [15]:
for i in np.nditer(arr3[:,::2]):  # all rows, all columns, step=2
    print(i)

1
3
5
7
9
12


### Enumerated Iteration Using ndenumerate()

In [16]:
for indx, i in np.ndenumerate(arr3):
    print(indx, i)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 8
(2, 0) 9
(2, 1) 10
(2, 2) 12
(2, 3) 12
