### Search : where()

In [1]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 4, 4])

np.where(arr == 4)  # return index where the value is 4

(array([3, 5, 6], dtype=int32),)

In [2]:
np.where(arr%2 == 0) # return even numbers' index

(array([1, 3, 5, 6], dtype=int32),)

In [3]:
np.where(arr%2 == 1) # return odd numbers' index

(array([0, 2, 4], dtype=int32),)

### searchsorted() 寻找插入值index

In [7]:
# The searchsorted() method is assumed to be used on sorted arrays.
arr2 = np.array([1,2,3,5,6,7,8])
np.searchsorted(arr2, 4) # return index where the specific value should be inserted before it

# The method starts the search from the left and returns the first index where the number 7 is no longer larger than the next value.

3

In [19]:
np.searchsorted(arr2, 4, side='right')

3

In [11]:
np.searchsorted([1,2,3,4,5], [-10, 10, 2, 3])

array([0, 5, 1, 2], dtype=int32)

#### no matter start from which side, always return the insert index. if there are same numbers, count from left--->return the first same number index, count from right---->return the last same number index 

In [22]:
np.searchsorted([1,2,3,3,3,3,3,4,5], 3, side='right') # 从右边数，碰到相同的，插在其前面，返回该位置的index

7

In [21]:
np.searchsorted([1,2,3,3,3,3,3,4,5], 3) #从左边数，碰到相同的插在其前面

2