### sort

In [1]:
import numpy as np

In [3]:
arr = np.array([[5,8,3,2,4],[12,43,21,32,16]])
arr

array([[ 5,  8,  3,  2,  4],
       [12, 43, 21, 32, 16]])

In [4]:
np.sort(arr)

array([[ 2,  3,  4,  5,  8],
       [12, 16, 21, 32, 43]])

### filter

In [5]:
arr[arr>10]

array([12, 43, 21, 32, 16])

In [6]:
arr2 = np.array([2,4,3,6,5,9,-1,-5,-10])

In [7]:
arr2[arr2%2==0]

array([  2,   4,   6, -10])