### Join two arrays

#### Concatenate

In [2]:
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.concatenate((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


In [3]:
arr3 = np.concatenate((arr1, arr2),axis=0)
arr3

array([1, 2, 3, 4, 5, 6])

In [4]:
arr3 = np.array([[1, 2], [3, 4]])

arr4 = np.array([[5, 6], [7, 8]])

arr = np.concatenate((arr1, arr2), axis=1) # join columns

print(arr)

[[1 2 5 6]
 [3 4 7 8]]


In [5]:
arr3 = np.concatenate((arr1, arr2), axis=0)
arr3

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

#### Stack

In [6]:
arr5 = np.array([1,2,3,4])
arr6 = np.array([5,6,7,8])

np.stack((arr5,arr6),axis=1)

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [7]:
np.stack((arr5,arr6),axis=0)

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [8]:
# stacking along rows
np.hstack((arr5, arr6)) # 左右叠一起

array([1, 2, 3, 4, 5, 6, 7, 8])

In [9]:
# stacking along columns
np.vstack((arr5, arr6)) #上下叠一起

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [10]:
# stacking along depth
np.dstack((arr5, arr6)) # 转化成vertical 左右叠一起

array([[[1, 5],
        [2, 6],
        [3, 7],
        [4, 8]]])

In [3]:
np.column_stack(([1,2,3],[4,5,6])) 

array([[1, 4],
       [2, 5],
       [3, 6]])

In [4]:
np.column_stack(([[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]])) # 第一个array的第一行和第二个array的第一行 

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [5]:
np.vstack(([[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]))

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [6]:
np.hstack(([[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]))

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [9]:
print(np.stack(([[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]),axis=0))

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [8]:
np.stack(([[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]),axis=1)

array([[[1, 2, 3],
        [1, 2, 3]],

       [[4, 5, 6],
        [4, 5, 6]]])

In [10]:
np.hstack(([[1],[2],[3]],[[4],[5],[6]]))

array([[1, 4],
       [2, 5],
       [3, 6]])